//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_WCF_Svc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thermo.com/informatics/xmlns/limswebservice", ConfigurationName="LIMS_WCF_Svc.ILIMSWebService")]
    public interface ILIMSWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/Process", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ProcessRes" +
            "ponse")]
        System.Threading.Tasks.Task<string> ProcessAsync(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/CheckAuth", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/CheckAuthR" +
            "esponse")]
        System.Threading.Tasks.Task<string> CheckAuthAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetAllLogF" +
            "ilesResponse")]
        System.Threading.Tasks.Task<object> GetAllLogFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/EraseAllLogFiles", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/EraseAllLo" +
            "gFilesResponse")]
        System.Threading.Tasks.Task<string> EraseAllLogFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/GetSingleLogFile", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/GetSingleL" +
            "ogFileResponse")]
        System.Threading.Tasks.Task<object> GetSingleLogFileAsync(string transaction, string direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/LogSOAPMessages", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/LogSOAPMes" +
            "sagesResponse")]
        System.Threading.Tasks.Task<bool> LogSOAPMessagesAsync(bool logging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thermo.com/informatics/xmlns/limswebservice/ViewLogStatus", ReplyAction="http://www.thermo.com/informatics/xmlns/limswebservice/ILIMSWebService/ViewLogSta" +
            "tusResponse")]
        System.Threading.Tasks.Task<bool> ViewLogStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ILIMSWebServiceChannel : LIMS_WCF_Svc.ILIMSWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LIMSWebServiceClient : System.ServiceModel.ClientBase<LIMS_WCF_Svc.ILIMSWebService>, LIMS_WCF_Svc.ILIMSWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LIMSWebServiceClient() : 
                base(LIMSWebServiceClient.GetDefaultBinding(), LIMSWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttp_ILIMSWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LIMSWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(LIMSWebServiceClient.GetBindingForEndpoint(endpointConfiguration), LIMSWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LIMSWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LIMSWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LIMSWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LIMSWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LIMSWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ProcessAsync(string request)
        {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> CheckAuthAsync()
        {
            return base.Channel.CheckAuthAsync();
        }
        
        public System.Threading.Tasks.Task<object> GetAllLogFilesAsync()
        {
            return base.Channel.GetAllLogFilesAsync();
        }
        
        public System.Threading.Tasks.Task<string> EraseAllLogFilesAsync()
        {
            return base.Channel.EraseAllLogFilesAsync();
        }
        
        public System.Threading.Tasks.Task<object> GetSingleLogFileAsync(string transaction, string direction)
        {
            return base.Channel.GetSingleLogFileAsync(transaction, direction);
        }
        
        public System.Threading.Tasks.Task<bool> LogSOAPMessagesAsync(bool logging)
        {
            return base.Channel.LogSOAPMessagesAsync(logging);
        }
        
        public System.Threading.Tasks.Task<bool> ViewLogStatusAsync()
        {
            return base.Channel.ViewLogStatusAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttp_ILIMSWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttp_ILIMSWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56104/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LIMSWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttp_ILIMSWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LIMSWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttp_ILIMSWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttp_ILIMSWebService,
        }
    }
}
