using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MOO.DAL.ToLive.Enums
{
    public enum  ConcAnalyticsGnrlGroup
    {
        /// <summary>
        /// Used on Analytics Line Detail under heading "What could help run faster"
        /// </summary>
        Actionable_Parameters,
        /// <summary>
        /// Used for pareto chart on Analytics line detail under heading "What is preventing us from going further"
        /// </summary>
        Pareto,
        /// <summary>
        /// Used for summary information on Analytics summary for Line
        /// </summary>
        Summary,
        /// <summary>
        /// Used for summary information on Analytics summary for Step and Plant
        /// </summary>
        Summary_Aggregated,
        /// <summary>
        /// Used for Conc Line impacts (bar chart) on Analytics line summary for Each Line
        /// </summary>
        Impact,
        /// <summary>
        /// Used for Conc Line impacts (bar chart) on Analytics line summary for Step and Plant
        /// </summary>
        Impact_Aggregated,
        /// <summary>
        /// Used on floatation dashboard
        /// </summary>
        Floatation_Run_Faster,
        /// <summary>
        /// used in Floatation Potential Dashboard, data is obtained from hdq
        /// </summary>
        Floatation_Potential,
        /// <summary>
        /// used in Floatation Potential Dashboard, data is generated by MOO Job
        /// </summary>
        Floatation_Potential_MOO,
        /// <summary>
        /// Used for the donut chart page showing percentage of constraints
        /// </summary>
        Donut_Plot,
        /// <summary>
        /// Used on the conc_analytics line summary for the percent iron recovery
        /// </summary>
        Floatation_Impact_Metrics
    }
}
